import type { ComponentType } from "react";
import type { SupportLevel } from "../../types/demo";
import {
A1,
  A1Code,
  A2,
  A2Code,
  A3,
  A3Code,
  A4,
  A4Code,
  A5,
  A5Code,
  A6,
  A6Code,
  B1,
  B1Code,
  B2,
  B2Code,
  B3,
  B3Code,
  B4,
  B4Code,
  C1,
  C1Code,
  C2,
  C2Code,
  C3,
  C3Code,
  C4,
  C4Code,
  D1,
  D1Code,
  D2,
  D2Code,
  D3,
  D3Code,
  D4,
  D4Code,
  D5,
  D5Code,
  D6,
  D6Code,
  D7,
  D7Code,
  E1,
  E1Code,
  E2,
  E2Code,
  E3,
  E3Code,
  E4,
  E4Code,
  E5,
  E5Code,
  F1,
  F1Code,
  F2,
  F2Code,
  F3,
  F3Code,
  F4,
  F4Code,
  G1,
  G1Code,
  G2,
  G2Code,
  G3,
  G3Code,
  G4,
  G4Code,
  G5,
  G5Code,
  H1,
  H1Code,
  H2,
  H2Code,
  H3,
  H3Code,
  H4,
  H4Code,
  I1,
  I1Code,
  I2,
  I2Code,
  I3,
  I3Code,
  I4,
  I4Code,
  J1,
  J1Code,
  J2,
  J2Code,
  J3,
  J3Code,
  K1,
  K1Code,
  K2,
  K2Code,
  K3,
  K3Code,
  K4,
  K4Code,
  L1,
  L1Code,
  L2,
  L2Code,
  L3,
  L3Code,
  M1,
  M1Code,
  M2,
  M2Code,
} from "./index";

interface DemoDefinition {
  id: string;
  title: string;
  description: string;
  support: SupportLevel;
  code: string;
  Component: ComponentType;
}

interface DemoCategory {
  id: string;
  title: string;
  demos: DemoDefinition[];
}

export const demoCategories: DemoCategory[] = [
  {
    id: "A",
    title: "Core Keyframe Animations",
    demos: [
      { id: "A1", title: "Basic @keyframes Bounce", description: "The foundation: @keyframes with from/to, infinite alternate, ease-in-out.", support: "widely-available", code: A1Code, Component: A1 },
      { id: "A2", title: "Multi-Stop Heartbeat", description: "Five-stop @keyframes with precise timing for a double-beat pulse.", support: "widely-available", code: A2Code, Component: A2 },
      { id: "A3", title: "animation-fill-mode", description: "Side-by-side comparison of none / forwards / both — controls state before and after animation.", support: "widely-available", code: A3Code, Component: A3 },
      { id: "A4", title: "animation-direction", description: "All four direction values: normal, reverse, alternate, and alternate-reverse.", support: "widely-available", code: A4Code, Component: A4 },
      { id: "A5", title: "animation-play-state", description: "Toggle between running and paused via a React state change — no CSS duplication.", support: "widely-available", code: A5Code, Component: A5 },
      { id: "A6", title: "Multiple Simultaneous Animations", description: "Three independent @keyframes on one element — spin, scale pulse, and hue-rotate running concurrently.", support: "widely-available", code: A6Code, Component: A6 },
    ],
  },
  {
    id: "B",
    title: "Easing Functions",
    demos: [
      { id: "B1", title: "Cubic-Bezier Curves", description: "Visual comparison of four distinct cubic-bezier easing functions side by side.", support: "widely-available", code: B1Code, Component: B1 },
      { id: "B2", title: "steps() — Discrete Frames", description: "steps(n, end) creates frame-by-frame animation — ideal for sprite sheets and counters.", support: "widely-available", code: B2Code, Component: B2 },
      { id: "B3", title: "steps() Typewriter", description: "Classic typewriter reveal using steps(n) on width combined with a blinking cursor animation.", support: "widely-available", code: B3Code, Component: B3 },
      { id: "B4", title: "linear() Spring Physics", description: "The new linear() easing function enables arbitrary piecewise curves — here approximating spring physics.", support: "baseline-2024", code: B4Code, Component: B4 },
    ],
  },
  {
    id: "C",
    title: "CSS Transitions",
    demos: [
      { id: "C1", title: "Multi-Property Card Hover", description: "Simultaneous transition of transform, box-shadow, background, and border-color with an overshoot curve.", support: "widely-available", code: C1Code, Component: C1 },
      { id: "C2", title: "transition-behavior: allow-discrete", description: "Enables transitioning display: none — element fades in/out smoothly with @starting-style.", support: "baseline-2024", code: C2Code, Component: C2 },
      { id: "C3", title: "@starting-style DOM Insertion", description: "Newly added DOM elements transition in from their @starting-style values — no JS animation needed.", support: "baseline-2024", code: C3Code, Component: C3 },
      { id: "C4", title: "Animated <dialog> Entry & Exit", description: "Native HTML dialog with smooth open/close transitions using @starting-style + overlay allow-discrete.", support: "baseline-2024", code: C4Code, Component: C4 },
    ],
  },
  {
    id: "D",
    title: "Scroll-Driven Animations",
    demos: [
      { id: "D1", title: "Scroll Progress Bar", description: "Pure CSS reading progress bar — animation-timeline: scroll(self block) with zero JavaScript.", support: "baseline-2024", code: D1Code, Component: D1 },
      { id: "D2", title: "Fade-In on Scroll (view())", description: "Elements animate as they enter the viewport using animation-timeline: view() — no IntersectionObserver.", support: "baseline-2024", code: D2Code, Component: D2 },
      { id: "D3", title: "CSS Parallax", description: "Background moves at a different speed than content — pure CSS scroll-linked parallax effect.", support: "baseline-2024", code: D3Code, Component: D3 },
      { id: "D4", title: "animation-range: entry / cover", description: "Cards scale in precisely as they enter the scroller, using named animation-range values.", support: "baseline-2024", code: D4Code, Component: D4 },
      { id: "D5", title: "Named scroll-timeline", description: "A named timeline on the scroller drives a sibling's conic progress ring animation.", support: "baseline-2024", code: D5Code, Component: D5 },
      { id: "D6", title: "Named view-timeline", description: "view-timeline on the subject element — child element reads it by name to reveal a progress bar.", support: "baseline-2024", code: D6Code, Component: D6 },
      { id: "D7", title: "animation-range: contain", description: "Content animates while the element is fully inside the scroll container, using contain range.", support: "baseline-2024", code: D7Code, Component: D7 },
    ],
  },
  {
    id: "E",
    title: "View Transitions API",
    demos: [
      { id: "E1", title: "SPA State Swap", description: "document.startViewTransition() wraps a state change with a smooth cross-fade by default.", support: "new-2025", code: E1Code, Component: E1 },
      { id: "E2", title: "Shared Element Hero Morph", description: "view-transition-name connects a thumbnail to a full-size element — the browser auto-morphs position and size.", support: "new-2025", code: E2Code, Component: E2 },
      { id: "E3", title: "Custom Directional Slide", description: "Override ::view-transition-old/new to create directional slide-in/slide-out animations.", support: "new-2025", code: E3Code, Component: E3 },
      { id: "E4", title: "view-transition-class Batch", description: "Assign a class to multiple named elements and style all their transitions at once.", support: "experimental", code: E4Code, Component: E4 },
      { id: "E5", title: ":active-view-transition-type()", description: "Style transitions differently based on a named type: push forward vs pull back.", support: "experimental", code: E5Code, Component: E5 },
    ],
  },
  {
    id: "F",
    title: "@property — Typed Custom Properties",
    demos: [
      { id: "F1", title: "Animated Gradient Color Stops", description: "@property registers typed <color> variables — gradients can now cross-fade between two palettes.", support: "baseline-2024", code: F1Code, Component: F1 },
      { id: "F2", title: "Conic Gradient Pie Sweep", description: "@property --sweep: <angle> drives a conic-gradient like a clock hand sweeping from 0° to 360°.", support: "baseline-2024", code: F2Code, Component: F2 },
      { id: "F3", title: "Rotating Gradient Border", description: "@property --angle combined with conic-gradient on a ::before pseudo-element creates an animated border.", support: "baseline-2024", code: F3Code, Component: F3 },
      { id: "F4", title: "Animated Theme Hue", description: "One @property --hue: <number> drives an entire palette of oklch swatches — update one value, shift everything.", support: "baseline-2024", code: F4Code, Component: F4 },
    ],
  },
  {
    id: "G",
    title: "3D Transforms & Perspective",
    demos: [
      { id: "G1", title: "Individual Transform Properties", description: "translate, rotate, and scale as standalone CSS properties — each animates and composes independently.", support: "widely-available", code: G1Code, Component: G1 },
      { id: "G2", title: "3D Card Flip", description: "rotateY(180deg) with transform-style: preserve-3d and backface-visibility: hidden on front and back faces.", support: "widely-available", code: G2Code, Component: G2 },
      { id: "G3", title: "CSS 3D Cube", description: "Six faces built with translateZ and rotateX/Y, spinning continuously with transform-style: preserve-3d.", support: "widely-available", code: G3Code, Component: G3 },
      { id: "G4", title: "Perspective Text Tilt", description: "Tracks mouse position to rotate text in 3D — perspective on parent, rotateX/Y on child.", support: "widely-available", code: G4Code, Component: G4 },
      { id: "G5", title: "transform-origin Explorer", description: "Same rotation animation applied with five different transform-origin values, showing their visual impact.", support: "widely-available", code: G5Code, Component: G5 },
    ],
  },
  {
    id: "H",
    title: "CSS Motion Path",
    demos: [
      { id: "H1", title: "offset-path: path() SVG Orbit", description: "Element follows a custom SVG path string — offset-rotate: auto orients it to the path tangent.", support: "baseline-2024", code: H1Code, Component: H1 },
      { id: "H2", title: "offset-path: circle() Solar System", description: "Two planets orbit a sun via basic shape paths — one forward, one reversed, different speeds.", support: "baseline-2024", code: H2Code, Component: H2 },
      { id: "H3", title: "offset-path: ray() Burst", description: "Eight particles radiate from center along ray() paths at 45° intervals, staggered with delays.", support: "baseline-2024", code: H3Code, Component: H3 },
      { id: "H4", title: "offset-path: ellipse() Auto-Orient Car", description: "A car emoji follows an elliptical track — offset-rotate: auto always faces the direction of travel.", support: "baseline-2024", code: H4Code, Component: H4 },
    ],
  },
  {
    id: "I",
    title: "clip-path Animations",
    demos: [
      { id: "I1", title: "inset() Wipe Reveal", description: "clip-path: inset() sweeps from right to left — a classic reveal transition with rounded corners.", support: "widely-available", code: I1Code, Component: I1 },
      { id: "I2", title: "circle() Radial Spotlight", description: "Spotlight expands from center on hover — clip-path: circle() transitioning from 0% to 50%.", support: "widely-available", code: I2Code, Component: I2 },
      { id: "I3", title: "polygon() Shape Morph", description: "Morphing between a 10-point star and a 6-point hexagon — vertex count must match for interpolation.", support: "widely-available", code: I3Code, Component: I3 },
      { id: "I4", title: "path() Blob Morph", description: "Organic blob morphing via three-keyframe clip-path: path() animation — same SVG command structure required.", support: "widely-available", code: I4Code, Component: I4 },
    ],
  },
  {
    id: "J",
    title: "Filters & Backdrop",
    demos: [
      { id: "J1", title: "filter Chain Transition", description: "Multi-function filter chain: blur + saturate + hue-rotate all transition simultaneously on hover.", support: "widely-available", code: J1Code, Component: J1 },
      { id: "J2", title: "backdrop-filter Glassmorphism", description: "backdrop-filter: blur() transitions from 0 to 16px on hover, revealing a frosted glass effect.", support: "widely-available", code: J2Code, Component: J2 },
      { id: "J3", title: "drop-shadow Neon Glow Pulse", description: "Stacked drop-shadow() filters animated with alternating keyframes create a neon breathing glow.", support: "widely-available", code: J3Code, Component: J3 },
    ],
  },
  {
    id: "K",
    title: "Text Animations",
    demos: [
      { id: "K1", title: "Animated Gradient Text", description: "background-clip: text clips a moving 300%-wide linear-gradient — creates an infinite color shimmer.", support: "widely-available", code: K1Code, Component: K1 },
      { id: "K2", title: "Variable Font Weight Morph", description: "font-variation-settings: 'wght' animates from 100 to 900 — requires a variable font with weight axis.", support: "widely-available", code: K2Code, Component: K2 },
      { id: "K3", title: "Letter-Spacing Reveal", description: "Text expands from compressed letter-spacing: -0.1em to 0.12em with opacity fade-in on load.", support: "widely-available", code: K3Code, Component: K3 },
      { id: "K4", title: "Typewriter + Blinking Cursor", description: "Three lines type one after another using steps() on width — cursor blinks via a separate animation.", support: "widely-available", code: K4Code, Component: K4 },
    ],
  },
  {
    id: "L",
    title: "Size & Layout Transitions",
    demos: [
      { id: "L1", title: "interpolate-size: allow-keywords", description: "height: 0 → height: auto now animates natively in Chrome 129+ — the end of the max-height hack.", support: "experimental", code: L1Code, Component: L1 },
      { id: "L2", title: "calc-size() Fractional Auto", description: "calc-size(auto, size * 0.5) expands to exactly half the element's natural height — impossible before.", support: "experimental", code: L2Code, Component: L2 },
      { id: "L3", title: "max-height Fallback (Legacy)", description: "The universal but imprecise accordion technique — max-height: 0 to a large number. Compare with L1.", support: "widely-available", code: L3Code, Component: L3 },
    ],
  },
  {
    id: "M",
    title: "Color & Animation Composition",
    demos: [
      { id: "M1", title: "oklch() Color Space Transitions", description: "oklch stays perceptually uniform through hue rotation — compare the midpoint vs HSL which dips grey.", support: "baseline-2024", code: M1Code, Component: M1 },
      { id: "M2", title: "animation-composition", description: "replace vs accumulate vs add: how stacked float + drift animations compose when both set transform.", support: "baseline-2024", code: M2Code, Component: M2 },
    ],
  },
];
