import type { ComponentType } from "react";
import type { SupportLevel } from "../../types/demo";
import {
KeyframesBasicBounce,
  KeyframesBasicBounceCode,
  KeyframesMultiStopHeartbeat,
  KeyframesMultiStopHeartbeatCode,
  KeyframesFillMode,
  KeyframesFillModeCode,
  KeyframesDirection,
  KeyframesDirectionCode,
  KeyframesPlayState,
  KeyframesPlayStateCode,
  KeyframesMultipleAnimations,
  KeyframesMultipleAnimationsCode,
  EasingCubicBezier,
  EasingCubicBezierCode,
  EasingStepsDiscreteFrames,
  EasingStepsDiscreteFramesCode,
  EasingStepsTypewriter,
  EasingStepsTypewriterCode,
  EasingLinearSpring,
  EasingLinearSpringCode,
  TransitionsMultiPropertyHover,
  TransitionsMultiPropertyHoverCode,
  TransitionsAllowDiscrete,
  TransitionsAllowDiscreteCode,
  TransitionsStartingStyleInsertion,
  TransitionsStartingStyleInsertionCode,
  TransitionsDialogEntryExit,
  TransitionsDialogEntryExitCode,
  ScrollProgressBar,
  ScrollProgressBarCode,
  ScrollFadeOnView,
  ScrollFadeOnViewCode,
  ScrollCssParallax,
  ScrollCssParallaxCode,
  ScrollAnimationRangeEntryCover,
  ScrollAnimationRangeEntryCoverCode,
  ScrollNamedScrollTimeline,
  ScrollNamedScrollTimelineCode,
  ScrollNamedViewTimeline,
  ScrollNamedViewTimelineCode,
  ScrollAnimationRangeContain,
  ScrollAnimationRangeContainCode,
  ViewTransitionsSpaStateSwap,
  ViewTransitionsSpaStateSwapCode,
  ViewTransitionsSharedHeroMorph,
  ViewTransitionsSharedHeroMorphCode,
  ViewTransitionsCustomDirectionalSlide,
  ViewTransitionsCustomDirectionalSlideCode,
  ViewTransitionsClassBatch,
  ViewTransitionsClassBatchCode,
  ViewTransitionsTransitionType,
  ViewTransitionsTransitionTypeCode,
  PropertyGradientColorStops,
  PropertyGradientColorStopsCode,
  PropertyConicSweep,
  PropertyConicSweepCode,
  PropertyRotatingGradientBorder,
  PropertyRotatingGradientBorderCode,
  PropertyThemeHue,
  PropertyThemeHueCode,
  TransformsIndividualProperties,
  TransformsIndividualPropertiesCode,
  TransformsCardFlip,
  TransformsCardFlipCode,
  Transforms3dCube,
  Transforms3dCubeCode,
  TransformsPerspectiveTextTilt,
  TransformsPerspectiveTextTiltCode,
  TransformsOriginExplorer,
  TransformsOriginExplorerCode,
  MotionPathSvgOrbit,
  MotionPathSvgOrbitCode,
  MotionPathCircleSolarSystem,
  MotionPathCircleSolarSystemCode,
  MotionPathRayBurst,
  MotionPathRayBurstCode,
  MotionPathEllipseAutoOrient,
  MotionPathEllipseAutoOrientCode,
  ClipPathInsetWipeReveal,
  ClipPathInsetWipeRevealCode,
  ClipPathCircleRadialSpotlight,
  ClipPathCircleRadialSpotlightCode,
  ClipPathPolygonShapeMorph,
  ClipPathPolygonShapeMorphCode,
  ClipPathPathBlobMorph,
  ClipPathPathBlobMorphCode,
  FiltersFilterChainTransition,
  FiltersFilterChainTransitionCode,
  FiltersBackdropGlassmorphism,
  FiltersBackdropGlassmorphismCode,
  FiltersDropShadowNeonGlow,
  FiltersDropShadowNeonGlowCode,
  TextAnimatedGradient,
  TextAnimatedGradientCode,
  TextVariableFontWeightMorph,
  TextVariableFontWeightMorphCode,
  TextLetterSpacingReveal,
  TextLetterSpacingRevealCode,
  TextTypewriterCursor,
  TextTypewriterCursorCode,
  SizeInterpolateSize,
  SizeInterpolateSizeCode,
  SizeCalcSizeFractionalAuto,
  SizeCalcSizeFractionalAutoCode,
  SizeMaxHeightFallback,
  SizeMaxHeightFallbackCode,
  ColorOklchTransitions,
  ColorOklchTransitionsCode,
  ColorAnimationComposition,
  ColorAnimationCompositionCode,
} from "./index";

interface DemoDefinition {
  id: string;
  title: string;
  description: string;
  support: SupportLevel;
  code: string;
  Component: ComponentType;
}

interface DemoCategory {
  id: string;
  title: string;
  demos: DemoDefinition[];
}

export const demoCategories: DemoCategory[] = [
  {
    id: "keyframes",
    title: "Core Keyframe Animations",
    demos: [
      { id: "keyframes-basic-bounce", title: "Basic @keyframes Bounce", description: "The foundation: @keyframes with from/to, infinite alternate, ease-in-out.", support: "widely-available", code: KeyframesBasicBounceCode, Component: KeyframesBasicBounce },
      { id: "keyframes-multi-stop-heartbeat", title: "Multi-Stop Heartbeat", description: "Five-stop @keyframes with precise timing for a double-beat pulse.", support: "widely-available", code: KeyframesMultiStopHeartbeatCode, Component: KeyframesMultiStopHeartbeat },
      { id: "keyframes-fill-mode", title: "animation-fill-mode", description: "Side-by-side comparison of none / forwards / both — controls state before and after animation.", support: "widely-available", code: KeyframesFillModeCode, Component: KeyframesFillMode },
      { id: "keyframes-direction", title: "animation-direction", description: "All four direction values: normal, reverse, alternate, and alternate-reverse.", support: "widely-available", code: KeyframesDirectionCode, Component: KeyframesDirection },
      { id: "keyframes-play-state", title: "animation-play-state", description: "Toggle between running and paused via a React state change — no CSS duplication.", support: "widely-available", code: KeyframesPlayStateCode, Component: KeyframesPlayState },
      { id: "keyframes-multiple-animations", title: "Multiple Simultaneous Animations", description: "Three independent @keyframes on one element — spin, scale pulse, and hue-rotate running concurrently.", support: "widely-available", code: KeyframesMultipleAnimationsCode, Component: KeyframesMultipleAnimations },
    ],
  },
  {
    id: "easing",
    title: "Easing Functions",
    demos: [
      { id: "easing-cubic-bezier", title: "Cubic-Bezier Curves", description: "Visual comparison of four distinct cubic-bezier easing functions side by side.", support: "widely-available", code: EasingCubicBezierCode, Component: EasingCubicBezier },
      { id: "easing-steps-discrete-frames", title: "steps() — Discrete Frames", description: "steps(n, end) creates frame-by-frame animation — ideal for sprite sheets and counters.", support: "widely-available", code: EasingStepsDiscreteFramesCode, Component: EasingStepsDiscreteFrames },
      { id: "easing-steps-typewriter", title: "steps() Typewriter", description: "Classic typewriter reveal using steps(n) on width combined with a blinking cursor animation.", support: "widely-available", code: EasingStepsTypewriterCode, Component: EasingStepsTypewriter },
      { id: "easing-linear-spring", title: "linear() Spring Physics", description: "The new linear() easing function enables arbitrary piecewise curves — here approximating spring physics.", support: "baseline-2024", code: EasingLinearSpringCode, Component: EasingLinearSpring },
    ],
  },
  {
    id: "transitions",
    title: "CSS Transitions",
    demos: [
      { id: "transitions-multi-property-hover", title: "Multi-Property Card Hover", description: "Simultaneous transition of transform, box-shadow, background, and border-color with an overshoot curve.", support: "widely-available", code: TransitionsMultiPropertyHoverCode, Component: TransitionsMultiPropertyHover },
      { id: "transitions-allow-discrete", title: "transition-behavior: allow-discrete", description: "Enables transitioning display: none — element fades in/out smoothly with @starting-style.", support: "baseline-2024", code: TransitionsAllowDiscreteCode, Component: TransitionsAllowDiscrete },
      { id: "transitions-starting-style-insertion", title: "@starting-style DOM Insertion", description: "Newly added DOM elements transition in from their @starting-style values — no JS animation needed.", support: "baseline-2024", code: TransitionsStartingStyleInsertionCode, Component: TransitionsStartingStyleInsertion },
      { id: "transitions-dialog-entry-exit", title: "Animated <dialog> Entry & Exit", description: "Native HTML dialog with smooth open/close transitions using @starting-style + overlay allow-discrete.", support: "baseline-2024", code: TransitionsDialogEntryExitCode, Component: TransitionsDialogEntryExit },
    ],
  },
  {
    id: "scroll",
    title: "Scroll-Driven Animations",
    demos: [
      { id: "scroll-progress-bar", title: "Scroll Progress Bar", description: "Pure CSS reading progress bar — animation-timeline: scroll(self block) with zero JavaScript.", support: "baseline-2024", code: ScrollProgressBarCode, Component: ScrollProgressBar },
      { id: "scroll-fade-on-view", title: "Fade-In on Scroll (view())", description: "Elements animate as they enter the viewport using animation-timeline: view() — no IntersectionObserver.", support: "baseline-2024", code: ScrollFadeOnViewCode, Component: ScrollFadeOnView },
      { id: "scroll-css-parallax", title: "CSS Parallax", description: "Background moves at a different speed than content — pure CSS scroll-linked parallax effect.", support: "baseline-2024", code: ScrollCssParallaxCode, Component: ScrollCssParallax },
      { id: "scroll-animation-range-entry-cover", title: "animation-range: entry / cover", description: "Cards scale in precisely as they enter the scroller, using named animation-range values.", support: "baseline-2024", code: ScrollAnimationRangeEntryCoverCode, Component: ScrollAnimationRangeEntryCover },
      { id: "scroll-named-scroll-timeline", title: "Named scroll-timeline", description: "A named timeline on the scroller drives a sibling's conic progress ring animation.", support: "baseline-2024", code: ScrollNamedScrollTimelineCode, Component: ScrollNamedScrollTimeline },
      { id: "scroll-named-view-timeline", title: "Named view-timeline", description: "view-timeline on the subject element — child element reads it by name to reveal a progress bar.", support: "baseline-2024", code: ScrollNamedViewTimelineCode, Component: ScrollNamedViewTimeline },
      { id: "scroll-animation-range-contain", title: "animation-range: contain", description: "Content animates while the element is fully inside the scroll container, using contain range.", support: "baseline-2024", code: ScrollAnimationRangeContainCode, Component: ScrollAnimationRangeContain },
    ],
  },
  {
    id: "view-transitions",
    title: "View Transitions API",
    demos: [
      { id: "view-transitions-spa-state-swap", title: "SPA State Swap", description: "document.startViewTransition() wraps a state change with a smooth cross-fade by default.", support: "new-2025", code: ViewTransitionsSpaStateSwapCode, Component: ViewTransitionsSpaStateSwap },
      { id: "view-transitions-shared-hero-morph", title: "Shared Element Hero Morph", description: "view-transition-name connects a thumbnail to a full-size element — the browser auto-morphs position and size.", support: "new-2025", code: ViewTransitionsSharedHeroMorphCode, Component: ViewTransitionsSharedHeroMorph },
      { id: "view-transitions-custom-directional-slide", title: "Custom Directional Slide", description: "Override ::view-transition-old/new to create directional slide-in/slide-out animations.", support: "new-2025", code: ViewTransitionsCustomDirectionalSlideCode, Component: ViewTransitionsCustomDirectionalSlide },
      { id: "view-transitions-class-batch", title: "view-transition-class Batch", description: "Assign a class to multiple named elements and style all their transitions at once.", support: "experimental", code: ViewTransitionsClassBatchCode, Component: ViewTransitionsClassBatch },
      { id: "view-transitions-transition-type", title: ":active-view-transition-type()", description: "Style transitions differently based on a named type: push forward vs pull back.", support: "experimental", code: ViewTransitionsTransitionTypeCode, Component: ViewTransitionsTransitionType },
    ],
  },
  {
    id: "property",
    title: "@property — Typed Custom Properties",
    demos: [
      { id: "property-gradient-color-stops", title: "Animated Gradient Color Stops", description: "@property registers typed <color> variables — gradients can now cross-fade between two palettes.", support: "baseline-2024", code: PropertyGradientColorStopsCode, Component: PropertyGradientColorStops },
      { id: "property-conic-sweep", title: "Conic Gradient Pie Sweep", description: "@property --sweep: <angle> drives a conic-gradient like a clock hand sweeping from 0° to 360°.", support: "baseline-2024", code: PropertyConicSweepCode, Component: PropertyConicSweep },
      { id: "property-rotating-gradient-border", title: "Rotating Gradient Border", description: "@property --angle combined with conic-gradient on a ::before pseudo-element creates an animated border.", support: "baseline-2024", code: PropertyRotatingGradientBorderCode, Component: PropertyRotatingGradientBorder },
      { id: "property-theme-hue", title: "Animated Theme Hue", description: "One @property --hue: <number> drives an entire palette of oklch swatches — update one value, shift everything.", support: "baseline-2024", code: PropertyThemeHueCode, Component: PropertyThemeHue },
    ],
  },
  {
    id: "transforms",
    title: "3D Transforms & Perspective",
    demos: [
      { id: "transforms-individual-properties", title: "Individual Transform Properties", description: "translate, rotate, and scale as standalone CSS properties — each animates and composes independently.", support: "widely-available", code: TransformsIndividualPropertiesCode, Component: TransformsIndividualProperties },
      { id: "transforms-card-flip", title: "3D Card Flip", description: "rotateY(180deg) with transform-style: preserve-3d and backface-visibility: hidden on front and back faces.", support: "widely-available", code: TransformsCardFlipCode, Component: TransformsCardFlip },
      { id: "transforms-3d-cube", title: "CSS 3D Cube", description: "Six faces built with translateZ and rotateX/Y, spinning continuously with transform-style: preserve-3d.", support: "widely-available", code: Transforms3dCubeCode, Component: Transforms3dCube },
      { id: "transforms-perspective-text-tilt", title: "Perspective Text Tilt", description: "Tracks mouse position to rotate text in 3D — perspective on parent, rotateX/Y on child.", support: "widely-available", code: TransformsPerspectiveTextTiltCode, Component: TransformsPerspectiveTextTilt },
      { id: "transforms-origin-explorer", title: "transform-origin Explorer", description: "Same rotation animation applied with five different transform-origin values, showing their visual impact.", support: "widely-available", code: TransformsOriginExplorerCode, Component: TransformsOriginExplorer },
    ],
  },
  {
    id: "motion-path",
    title: "CSS Motion Path",
    demos: [
      { id: "motion-path-svg-orbit", title: "offset-path: path() SVG Orbit", description: "Element follows a custom SVG path string — offset-rotate: auto orients it to the path tangent.", support: "baseline-2024", code: MotionPathSvgOrbitCode, Component: MotionPathSvgOrbit },
      { id: "motion-path-circle-solar-system", title: "offset-path: circle() Solar System", description: "Two planets orbit a sun via basic shape paths — one forward, one reversed, different speeds.", support: "baseline-2024", code: MotionPathCircleSolarSystemCode, Component: MotionPathCircleSolarSystem },
      { id: "motion-path-ray-burst", title: "offset-path: ray() Burst", description: "Eight particles radiate from center along ray() paths at 45° intervals, staggered with delays.", support: "baseline-2024", code: MotionPathRayBurstCode, Component: MotionPathRayBurst },
      { id: "motion-path-ellipse-auto-orient", title: "offset-path: ellipse() Auto-Orient Car", description: "A car emoji follows an elliptical track — offset-rotate: auto always faces the direction of travel.", support: "baseline-2024", code: MotionPathEllipseAutoOrientCode, Component: MotionPathEllipseAutoOrient },
    ],
  },
  {
    id: "clip-path",
    title: "clip-path Animations",
    demos: [
      { id: "clip-path-inset-wipe-reveal", title: "inset() Wipe Reveal", description: "clip-path: inset() sweeps from right to left — a classic reveal transition with rounded corners.", support: "widely-available", code: ClipPathInsetWipeRevealCode, Component: ClipPathInsetWipeReveal },
      { id: "clip-path-circle-radial-spotlight", title: "circle() Radial Spotlight", description: "Spotlight expands from center on hover — clip-path: circle() transitioning from 0% to 50%.", support: "widely-available", code: ClipPathCircleRadialSpotlightCode, Component: ClipPathCircleRadialSpotlight },
      { id: "clip-path-polygon-shape-morph", title: "polygon() Shape Morph", description: "Morphing between a 10-point star and a 6-point hexagon — vertex count must match for interpolation.", support: "widely-available", code: ClipPathPolygonShapeMorphCode, Component: ClipPathPolygonShapeMorph },
      { id: "clip-path-path-blob-morph", title: "path() Blob Morph", description: "Organic blob morphing via three-keyframe clip-path: path() animation — same SVG command structure required.", support: "widely-available", code: ClipPathPathBlobMorphCode, Component: ClipPathPathBlobMorph },
    ],
  },
  {
    id: "filters",
    title: "Filters & Backdrop",
    demos: [
      { id: "filters-filter-chain-transition", title: "filter Chain Transition", description: "Multi-function filter chain: blur + saturate + hue-rotate all transition simultaneously on hover.", support: "widely-available", code: FiltersFilterChainTransitionCode, Component: FiltersFilterChainTransition },
      { id: "filters-backdrop-glassmorphism", title: "backdrop-filter Glassmorphism", description: "backdrop-filter: blur() transitions from 0 to 16px on hover, revealing a frosted glass effect.", support: "widely-available", code: FiltersBackdropGlassmorphismCode, Component: FiltersBackdropGlassmorphism },
      { id: "filters-drop-shadow-neon-glow", title: "drop-shadow Neon Glow Pulse", description: "Stacked drop-shadow() filters animated with alternating keyframes create a neon breathing glow.", support: "widely-available", code: FiltersDropShadowNeonGlowCode, Component: FiltersDropShadowNeonGlow },
    ],
  },
  {
    id: "text",
    title: "Text Animations",
    demos: [
      { id: "text-animated-gradient", title: "Animated Gradient Text", description: "background-clip: text clips a moving 300%-wide linear-gradient — creates an infinite color shimmer.", support: "widely-available", code: TextAnimatedGradientCode, Component: TextAnimatedGradient },
      { id: "text-variable-font-weight-morph", title: "Variable Font Weight Morph", description: "font-variation-settings: 'wght' animates from 100 to 900 — requires a variable font with weight axis.", support: "widely-available", code: TextVariableFontWeightMorphCode, Component: TextVariableFontWeightMorph },
      { id: "text-letter-spacing-reveal", title: "Letter-Spacing Reveal", description: "Text expands from compressed letter-spacing: -0.1em to 0.12em with opacity fade-in on load.", support: "widely-available", code: TextLetterSpacingRevealCode, Component: TextLetterSpacingReveal },
      { id: "text-typewriter-cursor", title: "Typewriter + Blinking Cursor", description: "Three lines type one after another using steps() on width — cursor blinks via a separate animation.", support: "widely-available", code: TextTypewriterCursorCode, Component: TextTypewriterCursor },
    ],
  },
  {
    id: "size",
    title: "Size & Layout Transitions",
    demos: [
      { id: "size-interpolate-size", title: "interpolate-size: allow-keywords", description: "height: 0 → height: auto now animates natively in Chrome 129+ — the end of the max-height hack.", support: "experimental", code: SizeInterpolateSizeCode, Component: SizeInterpolateSize },
      { id: "size-calc-size-fractional-auto", title: "calc-size() Fractional Auto", description: "calc-size(auto, size * 0.5) expands to exactly half the element's natural height — impossible before.", support: "experimental", code: SizeCalcSizeFractionalAutoCode, Component: SizeCalcSizeFractionalAuto },
      { id: "size-max-height-fallback", title: "max-height Fallback (Legacy)", description: "The universal but imprecise accordion technique — max-height: 0 to a large number. Compare with the interpolate-size demo.", support: "widely-available", code: SizeMaxHeightFallbackCode, Component: SizeMaxHeightFallback },
    ],
  },
  {
    id: "color",
    title: "Color & Animation Composition",
    demos: [
      { id: "color-oklch-transitions", title: "oklch() Color Space Transitions", description: "oklch stays perceptually uniform through hue rotation — compare the midpoint vs HSL which dips grey.", support: "baseline-2024", code: ColorOklchTransitionsCode, Component: ColorOklchTransitions },
      { id: "color-animation-composition", title: "animation-composition", description: "replace vs accumulate vs add: how stacked float + drift animations compose when both set transform.", support: "baseline-2024", code: ColorAnimationCompositionCode, Component: ColorAnimationComposition },
    ],
  },
];
