export const TAILWIND_DEMO_SAFELIST = `
-bottom-1
-translate-x-full
[animation-delay:0ms]
[animation-delay:100ms]
[animation-delay:150ms]
[animation-delay:200ms]
[animation-delay:300ms]
[animation-delay:400ms]
[animation:glitch_0.3s_ease-in-out_infinite]
[animation:typewriter_3s_steps(24)_1s_both,blink-caret_0.8s_step-end_infinite]
[perspective:800px]
absolute
animate-bounce
animate-spin
backdrop-blur-md
backdrop-blur-sm
bg-[conic-gradient(from_0deg,var(--color-accent-brand),var(--color-accent-brand-secondary),var(--color-status-warning),var(--color-accent-brand))]
bg-[length:200%_100%]
bg-[length:200%_auto]
bg-[length:auto_200%]
bg-accent-brand
bg-accent-brand-secondary
bg-accent-brand/10
bg-border-subtle
bg-clip-text
bg-gradient-to-b
bg-gradient-to-br
bg-gradient-to-r
bg-shell-sidebar-overlay
bg-shimmer-text
bg-status-error/20
bg-status-success
bg-status-success/20
bg-status-warning/20
bg-surface-card
bg-surface-card-subtle
bg-text-tertiary/50
blur-sm
border
border-2
border-4
border-accent-brand
border-accent-brand/30
border-border-subtle
border-r-2
border-status-success
border-t-accent-brand
border-t-accent-brand-secondary
border-transparent
bottom-0
duration-1000
duration-300
duration-500
ease-out
flex
focus:border-accent-brand
focus:ring-2
focus:ring-accent-brand/30
focus:shadow-glow-subtle
font-black
font-bold
font-medium
font-mono
font-semibold
from-accent-brand
from-accent-brand-secondary
from-accent-brand/30
from-accent-soft-strong
from-border-subtle
from-status-success
from-status-warning
from-transparent
gap-2
gap-3
group
group-hover:[transform:rotateX(8deg)_rotateY(-8deg)]
group-hover:blur-md
group-hover:opacity-100
group-hover:rotate-[360deg]
group-hover:scale-x-100
group-hover:text-status-warning
group-hover:translate-x-0
group-hover:translate-y-0
h-0.5
h-1.5
h-2
h-4
h-40
h-full
hover:-translate-y-1
hover:backdrop-blur-xl
hover:bg-surface-control
hover:border-border-strong
hover:scale-105
hover:shadow-glow
hover:shadow-glow-strong
hover:text-text-inverse
hover:tracking-[.3em]
hover:tracking-[0.3em]
inline-block
inline-flex
inset-0
inset-x-0
items-center
justify-center
left-0
mb-2
mr-2
mt-3
mx-4
mx-auto
opacity-50
opacity-75
origin-[70%_70%]
origin-left
outline-none
overflow-hidden
p-4
p-6
p-8
p-[2px]
placeholder:text-text-tertiary
px-4
px-5
px-6
px-8
py-3
py-4
relative
rounded-2xl
rounded-full
rounded-lg
rounded-xl
scale-x-0
shadow-glow-subtle
shadow-lg
shadow-xl
size-10
size-12
size-16
size-2
size-24
size-28
size-3
size-4
size-5
size-7
size-8
size-full
space-y-3
text-2xl
text-3xl
text-4xl
text-accent-brand
text-center
text-lg
text-sm
text-status-error
text-status-success
text-status-warning
text-text-inverse
text-text-primary
text-text-secondary
text-text-tertiary
text-transparent
text-xl
to-accent-brand
to-accent-brand-secondary
to-accent-soft
to-border-subtle
to-status-error
to-status-error/30
to-transparent
tracking-tight
transition-all
transition-colors
transition-transform
translate-y-full
via-accent-brand
via-accent-brand-secondary
via-status-error
via-text-tertiary/40
w-1/2
w-1/3
w-3/4
w-48
w-64
w-full
whitespace-nowrap

`;
